name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ".gitignore exists"
      id: gitignore-exists
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: ".gitignore exists"
        setup-command: ''
        command: "[ -f .gitignore ]"
        timeout: 1
        max-score: 1
    - name: README.md exists
      id: readme-md-exists
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: README.md exists
        setup-command: ''
        command: "[ -f README.md ]"
        timeout: 1
        max-score: 2
    - name: doc directory exists and contains at least one pdf file
      id: doc-directory-exists-and-contains-at-least-one-pdf-file
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: doc directory exists and contains at least one pdf file
        setup-command: ''
        command: test -d doc && test $(ls -U doc | grep -c .pdf) -ge 1
        timeout: 1
        max-score: 4
    - name: Java files in packages in src
      id: java-files-in-packages-in-src
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java files in packages in src
        setup-command: ''
        command: test -d src && test $(ls -U src | grep -c .java) -eq 0 && test $(ls
          -UR src/* | grep -c .java) -ge 1
        timeout: 1
        max-score: 8
    - name: No common generated files in the repo (.idea, out, iml, class, .DS_Store)
      id: no-common-generated-files-in-the-repo-idea-out-iml-class-ds_store
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: No common generated files in the repo (.idea, out, iml, class,
          .DS_Store)
        setup-command: ''
        command: "[ ! -e .idea ] && [ ! -e out ] && test $(ls -UAR | grep -c -e \\\\.iml
          -e \\\\.class -e \\\\.DS_Store) -eq 0"
        timeout: 1
        max-score: 16
    - name: Java files in src (not necessarily correctly in packages)
      id: java-files-in-src-not-necessarily-correctly-in-packages
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java files in src (not necessarily correctly in packages)
        setup-command: ''
        command: test -d src && test $(ls -UR src/* | grep -c .java) -ge 1
        timeout: 1
        max-score: 32
    - name: Scoring and Validating Jar Present ("scorechecker.jar")
      id: scoring-and-validating-jar-present-scorechecker-jar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Scoring and Validating Jar Present ("scorechecker.jar")
        setup-command: ''
        command: '[ -f "scorechecker.jar" ]'
        timeout: 1
        max-score: 64
    - name: Solver Jar Present ("solver.jar")
      id: solver-jar-present-solver-jar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Solver Jar Present ("solver.jar")
        setup-command: ''
        command: '[ -f "solver.jar" ]'
        timeout: 1
        max-score: 128
    - name: Scrabble Jar Present ("scrabble.jar")
      id: scrabble-jar-present-scrabble-jar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Scrabble Jar Present ("scrabble.jar")
        setup-command: ''
        command: '[ -f "scrabble.jar" ]'
        timeout: 1
        max-score: 256
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GITIGNORE-EXISTS_RESULTS: "${{steps.gitignore-exists.outputs.result}}"
        README-MD-EXISTS_RESULTS: "${{steps.readme-md-exists.outputs.result}}"
        DOC-DIRECTORY-EXISTS-AND-CONTAINS-AT-LEAST-ONE-PDF-FILE_RESULTS: "${{steps.doc-directory-exists-and-contains-at-least-one-pdf-file.outputs.result}}"
        JAVA-FILES-IN-PACKAGES-IN-SRC_RESULTS: "${{steps.java-files-in-packages-in-src.outputs.result}}"
        NO-COMMON-GENERATED-FILES-IN-THE-REPO-IDEA-OUT-IML-CLASS-DS_STORE_RESULTS: "${{steps.no-common-generated-files-in-the-repo-idea-out-iml-class-ds_store.outputs.result}}"
        JAVA-FILES-IN-SRC-NOT-NECESSARILY-CORRECTLY-IN-PACKAGES_RESULTS: "${{steps.java-files-in-src-not-necessarily-correctly-in-packages.outputs.result}}"
        SCORING-AND-VALIDATING-JAR-PRESENT-SCORECHECKER-JAR_RESULTS: "${{steps.scoring-and-validating-jar-present-scorechecker-jar.outputs.result}}"
        SOLVER-JAR-PRESENT-SOLVER-JAR_RESULTS: "${{steps.solver-jar-present-solver-jar.outputs.result}}"
        SCRABBLE-JAR-PRESENT-SCRABBLE-JAR_RESULTS: "${{steps.scrabble-jar-present-scrabble-jar.outputs.result}}"
      with:
        runners: gitignore-exists,readme-md-exists,doc-directory-exists-and-contains-at-least-one-pdf-file,java-files-in-packages-in-src,no-common-generated-files-in-the-repo-idea-out-iml-class-ds_store,java-files-in-src-not-necessarily-correctly-in-packages,scoring-and-validating-jar-present-scorechecker-jar,solver-jar-present-solver-jar,scrabble-jar-present-scrabble-jar
